name: Terraform Plan and Apply

on:
    workflow_dispatch:
        inputs:
            location:
                description: 'Azure location (e.g., eastus, westus)'
                required: true
                default: 'eastus'
            rg_name:
                description: 'Resource Group name'
                required: true
                default: 'tf-multiip-rg'
            num_ip_configs:
                description: 'Number of IPs to allocate'
                required: true
                default: '1'
            subscription_id:
                description: 'Azure Subscription ID'
                required: true
                default: '1c51d1c3-d83d-4d71-ace1-df3496eddac4'
            apply:
                description: 'Apply the Terraform plan'
                required: true
                default: false
                type: boolean
        
jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Azure Authentication
              id: login
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}